# ==============================================================================
# Base Makefile - Git Worktree Commands
# Generated by overlord - Do not edit manually (use overlord sync)
# ==============================================================================

.PHONY: help worktree-new worktree-list worktree-remove worktree-setup \
        worktree-attach worktree-sessions worktree-send worktree-read \
        worktree-archive worktree-archive-remove \
        tmux-send tmux-read tmux-list \
        _create_worktree_session

# Default worktree directory (inside project)
WORKTREE_DIR := .worktrees

# Counter file for auto-generated worktree names
COUNTER_FILE := $(WORKTREE_DIR)/.counter

# Shell functions for counter management
define read_counter
$(shell [ -f $(COUNTER_FILE) ] && cat $(COUNTER_FILE) || echo 0)
endef

define increment_counter
$(shell \
	mkdir -p $(WORKTREE_DIR); \
	COUNTER=$$([ -f $(COUNTER_FILE) ] && cat $(COUNTER_FILE) || echo 0); \
	NEXT=$$((COUNTER + 1)); \
	echo $$NEXT > $(COUNTER_FILE); \
	echo $$COUNTER \
)
endef

# Word lists for name generation (20 adjectives × 20 nouns = 400 combinations)
ADJECTIVES := swift bright clever smooth quick clean sharp neat cool fast \
              bold calm clear crisp fresh light prime ready smart steady

NOUNS := fix task work dev patch branch code build test run \
         flow sync push pull draft spike probe check scan forge

# Generate deterministic name from counter
# Usage: $(call generate_name,counter_value)
define generate_name
$(shell \
	COUNTER=$(1); \
	ADJECTIVES="swift bright clever smooth quick clean sharp neat cool fast bold calm clear crisp fresh light prime ready smart steady"; \
	NOUNS="fix task work dev patch branch code build test run flow sync push pull draft spike probe check scan forge"; \
	ADJ_ARRAY=($$ADJECTIVES); \
	NOUN_ARRAY=($$NOUNS); \
	ADJ_IDX=$$((COUNTER % 20)); \
	NOUN_IDX=$$((COUNTER / 20 % 20)); \
	printf "%s_%s_%02d" "$${ADJ_ARRAY[$$ADJ_IDX]}" "$${NOUN_ARRAY[$$NOUN_IDX]}" $$COUNTER \
)
endef

# Check if tmux session exists
# Usage: $(call session_exists,session_name)
define session_exists
$(shell tmux has-session -t $(1) 2>/dev/null && echo 1 || echo 0)
endef

# Generate unique name (handles collisions)
# Returns: unique_name
define generate_unique_name
$(shell \
	COUNTER=$$($(increment_counter)); \
	NAME=$$($(call generate_name,$$COUNTER)); \
	while [ "$$($(call session_exists,$$NAME))" = "1" ]; do \
		NAME="$${NAME}_$$COUNTER"; \
	done; \
	echo $$NAME \
)
endef

# Show available commands
help:
	@echo "Worktree + Tmux Commands:"
	@echo ""
	@echo "Worktree Management:"
	@echo "  make worktree-new [BRANCH=<name>]        Create worktree + tmux session (auto-names if BRANCH omitted)"
	@echo "  make worktree-list                       List all worktrees"
	@echo "  make worktree-remove BRANCH=<name>       Remove worktree and kill tmux session"
	@echo "  make worktree-archive BRANCH=<name>      Archive logs from worktree to .worktrees/logs/"
	@echo "  make worktree-archive-remove BRANCH=<name>"
	@echo "                                           Archive logs then remove worktree"
	@echo "  make worktree-setup                      Run .worktree-setup.sh in current directory"
	@echo ""
	@echo "Tmux Session Management:"
	@echo "  make worktree-attach BRANCH=<name>       Attach to worktree's tmux session"
	@echo "  make worktree-sessions                   List tmux sessions for all worktrees"
	@echo ""
	@echo "Cross-Session Communication:"
	@echo "  make worktree-send BRANCH=<name> WINDOW=<window> CMD=\"<command>\""
	@echo "                                           Send command to worktree session window"
	@echo "  make worktree-read BRANCH=<name> WINDOW=<window>"
	@echo "                                           Read visible pane content from worktree"
	@echo ""
	@echo "Current Session Utilities (run from within tmux):"
	@echo "  make tmux-send WINDOW=<window> CMD=\"<command>\""
	@echo "                                           Send command to current session window"
	@echo "  make tmux-read WINDOW=<window>           Read visible pane content from window"
	@echo "  make tmux-list                           List all windows in current session"
	@echo ""
	@echo "Examples:"
	@echo "  make worktree-new                        Create worktree with auto-generated name"
	@echo "  make worktree-new BRANCH=fix-auth        Create worktree named 'fix-auth'"
	@echo "  make tmux-send WINDOW=shell CMD=\"make test\""
	@echo "  make tmux-read WINDOW=shell              Read test output"
	@echo "  make tmux-list                           Show available windows"
	@echo "  make worktree-send BRANCH=fix-auth WINDOW=shell CMD=\"make test\""
	@echo "  make worktree-attach BRANCH=fix-auth     Attach to 'fix-auth' session"
	@echo ""

# Create a new worktree with tmux session
# Usage: make worktree-new [BRANCH=<name>]
# If BRANCH omitted, generates name automatically
worktree-new:
	@# Determine branch name (auto-generate or use provided)
	@BRANCH_NAME="$(BRANCH)"; \
	if [ -z "$$BRANCH_NAME" ]; then \
		COUNTER=$$($(increment_counter)); \
		BRANCH_NAME=$$($(call generate_name,$$COUNTER)); \
		while tmux has-session -t "$$BRANCH_NAME" 2>/dev/null; do \
			BRANCH_NAME="$${BRANCH_NAME}_$$COUNTER"; \
		done; \
		echo "Auto-generated name: $$BRANCH_NAME"; \
	fi; \
	\
	WORKTREE_PATH="$(WORKTREE_DIR)/$$BRANCH_NAME"; \
	BRANCH_CREATED=0; \
	\
	mkdir -p $(WORKTREE_DIR); \
	\
	if git show-ref --verify --quiet refs/heads/$$BRANCH_NAME; then \
		echo "Branch '$$BRANCH_NAME' exists, creating worktree..."; \
		if ! git worktree add $$WORKTREE_PATH $$BRANCH_NAME 2>/dev/null; then \
			echo "Error: Failed to create worktree"; \
			exit 1; \
		fi; \
	else \
		echo "Creating new branch '$$BRANCH_NAME' and worktree..."; \
		if ! git worktree add -b $$BRANCH_NAME $$WORKTREE_PATH 2>/dev/null; then \
			echo "Error: Failed to create worktree"; \
			exit 1; \
		fi; \
		BRANCH_CREATED=1; \
	fi; \
	\
	if [ -f .gitignore ]; then \
		echo "Copying .gitignore to worktree..."; \
		cp .gitignore $$WORKTREE_PATH/; \
	fi; \
	\
	if [ -f .worktree-setup.sh ]; then \
		echo "Running .worktree-setup.sh..."; \
		chmod +x .worktree-setup.sh; \
		if ! (cd $$WORKTREE_PATH && ../.worktree-setup.sh); then \
			echo "Error: Setup script failed, rolling back..."; \
			git worktree remove --force $$WORKTREE_PATH 2>/dev/null || true; \
			if [ $$BRANCH_CREATED -eq 1 ]; then \
				git branch -D $$BRANCH_NAME 2>/dev/null || true; \
			fi; \
			exit 1; \
		fi; \
	else \
		echo "Warning: No .worktree-setup.sh found (continuing anyway)"; \
	fi; \
	\
	echo "Creating tmux session: $$BRANCH_NAME"; \
	$(MAKE) _create_worktree_session BRANCH=$$BRANCH_NAME WORKTREE_PATH=$$WORKTREE_PATH; \
	\
	echo ""; \
	echo "Worktree created successfully!"; \
	echo "  Branch: $$BRANCH_NAME"; \
	echo "  Path: $$WORKTREE_PATH"; \
	echo "  Session: $$BRANCH_NAME"; \
	echo ""; \
	echo "Attach with: make worktree-attach BRANCH=$$BRANCH_NAME"

# Internal: Create tmux session for worktree (called by worktree-new)
# Usage: make _create_worktree_session BRANCH=name WORKTREE_PATH=path
_create_worktree_session:
	@SESSION="$(BRANCH)"; \
	WORKTREE_DIR="$(WORKTREE_PATH)"; \
	\
	if tmux has-session -t "$$SESSION" 2>/dev/null; then \
		echo "Note: Tmux session '$$SESSION' already exists"; \
		exit 0; \
	fi; \
	\
	tmux new-session -d -s "$$SESSION" -c "$$WORKTREE_DIR" -n base; \
	\
	LOCAL_RC="$$WORKTREE_DIR/.tmux.local"; \
	MODE="override"; \
	\
	if [ -f "$$LOCAL_RC" ]; then \
		MODE_LINE=$$(grep -E '^[[:space:]]*MODE=' "$$LOCAL_RC" 2>/dev/null | head -n1 || true); \
		if [ -n "$$MODE_LINE" ]; then \
			MODE=$$(echo "$$MODE_LINE" | sed -E 's/^[[:space:]]*MODE=//; s/[[:space:]]*$$//'); \
		fi; \
	fi; \
	\
	if [ -f "$$LOCAL_RC" ] && [ "$$MODE" = "override" ]; then \
		TMUX_SESSION="$$SESSION" TMUX_PROJECT_DIR="$$WORKTREE_DIR" bash "$$LOCAL_RC"; \
	else \
		tmux rename-window -t "$${SESSION}:base" "editor"; \
		tmux send-keys -t "$${SESSION}:editor" "nvim" C-m; \
		tmux new-window -t "$$SESSION:" -n shell -c "$$WORKTREE_DIR"; \
		tmux new-window -t "$$SESSION:" -n git -c "$$WORKTREE_DIR"; \
		tmux send-keys -t "$${SESSION}:git" "git status" C-m; \
		\
		if [ -f "$$LOCAL_RC" ] && [ "$$MODE" = "merge" ]; then \
			TMUX_SESSION="$$SESSION" TMUX_PROJECT_DIR="$$WORKTREE_DIR" bash "$$LOCAL_RC"; \
		fi; \
	fi; \
	\
	tmux select-window -t "$${SESSION}:editor"

# List all worktrees
worktree-list:
	@git worktree list

# Remove a worktree and kill its tmux session
# Usage: make worktree-remove BRANCH=<name>
worktree-remove:
ifndef BRANCH
	$(error BRANCH is required. Usage: make worktree-remove BRANCH=<branch-name>)
endif
	@echo "Removing worktree and tmux session: $(BRANCH)"; \
	\
	if tmux has-session -t "$(BRANCH)" 2>/dev/null; then \
		echo "Killing tmux session: $(BRANCH)"; \
		tmux kill-session -t "$(BRANCH)"; \
	else \
		echo "No tmux session found: $(BRANCH)"; \
	fi; \
	\
	if [ -d "$(WORKTREE_DIR)/$(BRANCH)" ]; then \
		echo "Removing worktree: $(BRANCH)"; \
		git worktree remove $(WORKTREE_DIR)/$(BRANCH); \
		echo "Worktree removed: $(BRANCH)"; \
	else \
		echo "Warning: Worktree directory not found: $(WORKTREE_DIR)/$(BRANCH)"; \
	fi; \
	\
	echo "Cleanup complete: $(BRANCH)"

# Archive logs from a worktree to .worktrees/logs/<branch>/
# Usage: make worktree-archive BRANCH=<name>
worktree-archive:
ifndef BRANCH
	$(error BRANCH is required. Usage: make worktree-archive BRANCH=<branch-name>)
endif
	@WORKTREE_PATH="$(WORKTREE_DIR)/$(BRANCH)"; \
	LOG_DIR="$(WORKTREE_DIR)/logs/$(BRANCH)"; \
	\
	if [ ! -d "$$WORKTREE_PATH" ]; then \
		echo "Error: Worktree directory not found: $$WORKTREE_PATH"; \
		exit 1; \
	fi; \
	\
	mkdir -p "$$LOG_DIR"; \
	\
	echo "Archiving logs from $(BRANCH)..."; \
	\
	for LOG_FILE in WORKLOG.md REFLECTION.md TASK.md; do \
		if [ -f "$$WORKTREE_PATH/$$LOG_FILE" ]; then \
			cp "$$WORKTREE_PATH/$$LOG_FILE" "$$LOG_DIR/"; \
			echo "  Archived: $$LOG_FILE"; \
		fi; \
	done; \
	\
	if [ -n "$$(git -C "$$WORKTREE_PATH" diff --name-only 2>/dev/null)" ]; then \
		git -C "$$WORKTREE_PATH" diff > "$$LOG_DIR/changes.diff"; \
		echo "  Archived: changes.diff"; \
	fi; \
	\
	echo "Logs archived to: $$LOG_DIR"

# Archive logs and then remove worktree
# Usage: make worktree-archive-remove BRANCH=<name>
worktree-archive-remove:
ifndef BRANCH
	$(error BRANCH is required. Usage: make worktree-archive-remove BRANCH=<branch-name>)
endif
	@$(MAKE) worktree-archive BRANCH=$(BRANCH) && \
	$(MAKE) worktree-remove BRANCH=$(BRANCH)

# Attach to worktree's tmux session
# Usage: make worktree-attach BRANCH=<name>
worktree-attach:
ifndef BRANCH
	$(error BRANCH is required. Usage: make worktree-attach BRANCH=<branch-name>)
endif
	@if ! tmux has-session -t "$(BRANCH)" 2>/dev/null; then \
		echo "Error: Tmux session '$(BRANCH)' does not exist"; \
		echo "Create worktree first: make worktree-new BRANCH=$(BRANCH)"; \
		exit 1; \
	fi; \
	\
	if [ -n "$$TMUX" ]; then \
		echo "Switching to session: $(BRANCH)"; \
		tmux switch-client -t "$(BRANCH)"; \
	else \
		echo "Attaching to session: $(BRANCH)"; \
		tmux attach -t "$(BRANCH)"; \
	fi

# List tmux sessions for all worktrees
# Usage: make worktree-sessions
worktree-sessions:
	@echo "Tmux sessions for worktrees:"; \
	echo ""; \
	if ! git worktree list --porcelain 2>/dev/null | grep -q '^worktree'; then \
		echo "No worktrees found"; \
		exit 0; \
	fi; \
	\
	git worktree list --porcelain | while IFS= read -r line; do \
		if echo "$$line" | grep -q '^worktree'; then \
			WORKTREE_PATH=$$(echo "$$line" | sed 's/^worktree //'); \
			BRANCH_NAME=$$(basename "$$WORKTREE_PATH"); \
			\
			if echo "$$WORKTREE_PATH" | grep -q "$(WORKTREE_DIR)"; then \
				if tmux has-session -t "$$BRANCH_NAME" 2>/dev/null; then \
					WINDOWS=$$(tmux list-windows -t "$$BRANCH_NAME" 2>/dev/null | wc -l); \
					ATTACHED=$$(tmux list-sessions 2>/dev/null | grep "^$$BRANCH_NAME:" | grep -o 'attached' || echo "detached"); \
					printf "  %-30s  %d windows  %s\n" "$$BRANCH_NAME" $$WINDOWS "$$ATTACHED"; \
				else \
					printf "  %-30s  (no session)\n" "$$BRANCH_NAME"; \
				fi; \
			fi; \
		fi; \
	done; \
	echo ""

# Run setup script in current worktree
# Looks for .worktree-setup.sh in the project root
worktree-setup:
	@if [ -f .worktree-setup.sh ]; then \
		echo "Running .worktree-setup.sh..."; \
		chmod +x .worktree-setup.sh && ./.worktree-setup.sh; \
	else \
		echo "No .worktree-setup.sh found. Create one for custom setup."; \
	fi

# Send command to worktree's tmux session window
# Usage: make worktree-send BRANCH=<name> WINDOW=<window> CMD="<command>"
worktree-send:
ifndef BRANCH
	$(error BRANCH is required. Usage: make worktree-send BRANCH=<name> WINDOW=<window> CMD="<command>")
endif
ifndef WINDOW
	$(error WINDOW is required. Usage: make worktree-send BRANCH=<name> WINDOW=<window> CMD="<command>")
endif
ifndef CMD
	$(error CMD is required. Usage: make worktree-send BRANCH=<name> WINDOW=<window> CMD="<command>")
endif
	@SESSION="$(BRANCH)"; \
	WINDOW_NAME="$(WINDOW)"; \
	COMMAND="$(CMD)"; \
	\
	if ! tmux has-session -t "$$SESSION" 2>/dev/null; then \
		echo "Error: Tmux session '$$SESSION' does not exist"; \
		echo ""; \
		echo "Available worktree sessions:"; \
		$(MAKE) worktree-sessions 2>/dev/null || echo "  (none)"; \
		exit 1; \
	fi; \
	\
	if ! tmux list-windows -t "$$SESSION" 2>/dev/null | grep -q "^[0-9]*: $$WINDOW_NAME"; then \
		echo "Error: Window '$$WINDOW_NAME' does not exist in session '$$SESSION'"; \
		echo ""; \
		echo "Available windows in '$$SESSION':"; \
		tmux list-windows -t "$$SESSION" 2>/dev/null | awk '{print "  " $$2}' | sed 's/\*$$//'; \
		exit 1; \
	fi; \
	\
	echo "Sending to $$SESSION:$$WINDOW_NAME: $$COMMAND"; \
	tmux send-keys -t "$$SESSION:$$WINDOW_NAME" "$$COMMAND" C-m

# Read visible pane content from worktree's tmux session window
# Usage: make worktree-read BRANCH=<name> WINDOW=<window>
worktree-read:
ifndef BRANCH
	$(error BRANCH is required. Usage: make worktree-read BRANCH=<name> WINDOW=<window>)
endif
ifndef WINDOW
	$(error WINDOW is required. Usage: make worktree-read BRANCH=<name> WINDOW=<window>)
endif
	@SESSION="$(BRANCH)"; \
	WINDOW_NAME="$(WINDOW)"; \
	\
	if ! tmux has-session -t "$$SESSION" 2>/dev/null; then \
		echo "Error: Tmux session '$$SESSION' does not exist"; \
		echo ""; \
		echo "Available worktree sessions:"; \
		$(MAKE) worktree-sessions 2>/dev/null || echo "  (none)"; \
		exit 1; \
	fi; \
	\
	if ! tmux list-windows -t "$$SESSION" 2>/dev/null | grep -q "^[0-9]*: $$WINDOW_NAME"; then \
		echo "Error: Window '$$WINDOW_NAME' does not exist in session '$$SESSION'"; \
		echo ""; \
		echo "Available windows in '$$SESSION':"; \
		tmux list-windows -t "$$SESSION" 2>/dev/null | awk '{print "  " $$2}' | sed 's/\*$$//'; \
		exit 1; \
	fi; \
	\
	echo "Reading from $$SESSION:$$WINDOW_NAME:"; \
	echo "----------------------------------------"; \
	tmux capture-pane -t "$$SESSION:$$WINDOW_NAME" -p

# Send command to window in current tmux session
# Usage: make tmux-send WINDOW=<window> CMD="<command>"
tmux-send:
ifndef WINDOW
	$(error WINDOW is required. Usage: make tmux-send WINDOW=<window> CMD="<command>")
endif
ifndef CMD
	$(error CMD is required. Usage: make tmux-send WINDOW=<window> CMD="<command>")
endif
	@if [ -z "$$TMUX" ]; then \
		echo "Error: Not running inside tmux session"; \
		echo ""; \
		echo "This command must be run from within a tmux session."; \
		echo "Use 'overlord open' or 'make worktree-attach' to enter a session."; \
		exit 1; \
	fi; \
	\
	SESSION=$$(tmux display-message -p '#S'); \
	WINDOW_NAME="$(WINDOW)"; \
	COMMAND="$(CMD)"; \
	\
	if ! tmux list-windows -t "$$SESSION" 2>/dev/null | grep -q "^[0-9]*: $$WINDOW_NAME"; then \
		echo "Error: Window '$$WINDOW_NAME' does not exist in current session '$$SESSION'"; \
		echo ""; \
		echo "Available windows:"; \
		tmux list-windows -t "$$SESSION" 2>/dev/null | awk '{print "  " $$2}' | sed 's/\*$$//'; \
		exit 1; \
	fi; \
	\
	echo "Sending to $$SESSION:$$WINDOW_NAME: $$COMMAND"; \
	tmux send-keys -t "$$SESSION:$$WINDOW_NAME" "$$COMMAND" C-m

# Read visible pane content from window in current tmux session
# Usage: make tmux-read WINDOW=<window>
tmux-read:
ifndef WINDOW
	$(error WINDOW is required. Usage: make tmux-read WINDOW=<window>)
endif
	@if [ -z "$$TMUX" ]; then \
		echo "Error: Not running inside tmux session"; \
		echo ""; \
		echo "This command must be run from within a tmux session."; \
		echo "Use 'overlord open' or 'make worktree-attach' to enter a session."; \
		exit 1; \
	fi; \
	\
	SESSION=$$(tmux display-message -p '#S'); \
	WINDOW_NAME="$(WINDOW)"; \
	\
	if ! tmux list-windows -t "$$SESSION" 2>/dev/null | grep -q "^[0-9]*: $$WINDOW_NAME"; then \
		echo "Error: Window '$$WINDOW_NAME' does not exist in current session '$$SESSION'"; \
		echo ""; \
		echo "Available windows:"; \
		tmux list-windows -t "$$SESSION" 2>/dev/null | awk '{print "  " $$2}' | sed 's/\*$$//'; \
		exit 1; \
	fi; \
	\
	echo "Reading from $$SESSION:$$WINDOW_NAME:"; \
	echo "----------------------------------------"; \
	tmux capture-pane -t "$$SESSION:$$WINDOW_NAME" -p

# List all windows in current tmux session
# Usage: make tmux-list
tmux-list:
	@if [ -z "$$TMUX" ]; then \
		echo "Error: Not running inside tmux session"; \
		echo ""; \
		echo "This command must be run from within a tmux session."; \
		echo "Use 'overlord open' or 'make worktree-attach' to enter a session."; \
		exit 1; \
	fi; \
	\
	SESSION=$$(tmux display-message -p '#S'); \
	echo "Windows in session '$$SESSION':"; \
	echo ""; \
	tmux list-windows -t "$$SESSION" | while IFS=: read -r index rest; do \
		NAME=$$(echo "$$rest" | awk '{print $$1}' | sed 's/\*$$//'); \
		IS_ACTIVE=$$(echo "$$rest" | grep -q '\*' && echo " (active)" || echo ""); \
		printf "  %s%s\n" "$$NAME" "$$IS_ACTIVE"; \
	done; \
	echo ""

# ==============================================================================
# Go Makefile - Standard Go Commands
# Generated by overlord - Do not edit manually (use overlord sync)
# ==============================================================================

.PHONY: deps build install deploy run setup config init list info new add rm archive unarchive open activate deactivate sync test bench fmt vet clean

# Install dependencies
deps:
	go mod download

# Install binary to ~/.local/bin
install: build
	mkdir -p ~/.local/bin
	cp overlord ~/.local/bin/overlord
	@echo "Installed overlord to ~/.local/bin/overlord"

# Deploy to VPS (cross-compile for Linux and transfer)
# Usage: make deploy [VPS=hostname]
VPS ?= vps
deploy:
	@echo "Building for Linux amd64..."
	GOOS=linux GOARCH=amd64 go build -o overlord-linux ./cmd/overlord
	@echo "Deploying to $(VPS)..."
	scp overlord-linux $(VPS):/root/go/bin/overlord
	rm overlord-linux
	@echo "Deployed to $(VPS):/root/go/bin/overlord"

# Build the application
build:
	go build -o overlord ./cmd/overlord

# Run the application
run:
	go run ./cmd/overlord

# Set up overlord directories and configuration
setup:
	./overlord setup

# Open registry in editor
config:
	./overlord config

# Initialize directory with project template files
# Usage: make init [PATH=<path>] [LANG=go|py|ts|sol] [NAME=<name>] [DESC="description"]
init:
	./overlord init $(PATH) \
		$(if $(filter go,$(LANG)),--go) \
		$(if $(filter py,$(LANG)),--py) \
		$(if $(filter ts,$(LANG)),--ts) \
		$(if $(filter sol,$(LANG)),--sol) \
		$(if $(NAME),--name=$(NAME)) \
		$(if $(DESC),--description="$(DESC)")

# List projects (with optional filters)
# Usage: make list [CATEGORY=<cat>] [TAG=<tag>] [JSON=1] [ALL=1]
list:
	./overlord list $(if $(CATEGORY),--category=$(CATEGORY)) $(if $(TAG),--tag=$(TAG)) $(if $(JSON),--json) $(if $(ALL),--all)

# Show project info
info:
	./overlord info $(NAME)

# Create new project
# Usage: make new NAME=<name> CATEGORY=<cat> [LANG=go|py|ts|sol] [DESC="description"] [NO_GIT=1] [NO_OPEN=1]
new:
ifndef NAME
	$(error NAME is required. Usage: make new NAME=<name> CATEGORY=<cat> [LANG=go|py|ts|sol])
endif
ifndef CATEGORY
	$(error CATEGORY is required. Usage: make new NAME=<name> CATEGORY=<cat> [LANG=go|py|ts|sol])
endif
	./overlord new $(NAME) --category=$(CATEGORY) \
		$(if $(filter go,$(LANG)),--go) \
		$(if $(filter py,$(LANG)),--py) \
		$(if $(filter ts,$(LANG)),--ts) \
		$(if $(filter sol,$(LANG)),--sol) \
		$(if $(DESC),--description="$(DESC)") \
		$(if $(NO_GIT),--no-git) \
		$(if $(NO_OPEN),--no-open)

# Add existing project to registry
# Usage: make add NAME=<name> PATH=<path> [CATEGORY=<cat>] [LANG=go|py|ts|sol] [DESC="description"] [ALIAS=<alias>]
add:
ifndef NAME
	$(error NAME is required. Usage: make add NAME=<name> PATH=<path> [CATEGORY=<cat>] [LANG=go|py|ts|sol])
endif
ifndef PATH
	$(error PATH is required. Usage: make add NAME=<name> PATH=<path> [CATEGORY=<cat>] [LANG=go|py|ts|sol])
endif
	./overlord add $(NAME) $(PATH) \
		$(if $(CATEGORY),--category=$(CATEGORY)) \
		$(if $(filter go,$(LANG)),--go) \
		$(if $(filter py,$(LANG)),--py) \
		$(if $(filter ts,$(LANG)),--ts) \
		$(if $(filter sol,$(LANG)),--sol) \
		$(if $(DESC),--description="$(DESC)") \
		$(if $(ALIAS),--alias=$(ALIAS))

# Remove project from registry
# Usage: make rm NAME=<name>
rm:
ifndef NAME
	$(error NAME is required. Usage: make rm NAME=<name>)
endif
	./overlord rm $(NAME)

# Archive project to archive directory
# Usage: make archive NAME=<name> [YES=1]
archive:
ifndef NAME
	$(error NAME is required. Usage: make archive NAME=<name>)
endif
	./overlord archive $(NAME) $(if $(YES),--yes)

# Unarchive project from archive directory
# Usage: make unarchive NAME=<name> [CATEGORY=<cat>]
unarchive:
ifndef NAME
	$(error NAME is required. Usage: make unarchive NAME=<name> [CATEGORY=<cat>])
endif
	./overlord unarchive $(NAME) $(if $(CATEGORY),--category=$(CATEGORY))

# Open project workspace in tmux
# Usage: make open [NAME=<name>]
open:
	./overlord open $(NAME)

# Activate sync for a project
# Usage: make activate NAME=<name>
activate:
ifndef NAME
	$(error NAME is required. Usage: make activate NAME=<name>)
endif
	./overlord activate $(NAME)

# Deactivate sync for a project
# Usage: make deactivate NAME=<name>
deactivate:
ifndef NAME
	$(error NAME is required. Usage: make deactivate NAME=<name>)
endif
	./overlord deactivate $(NAME)

# Sync projects with storage machine
# Usage: make sync [NAME=<name>] [DRY_RUN=1] [FORCE=1]
sync:
	./overlord sync $(NAME) $(if $(DRY_RUN),--dry-run) $(if $(FORCE),--force)


# Run tests
test:
	go test -v ./...

# Run benchmarks
bench:
	go test -bench=. -benchmem ./...

# Format code
fmt:
	go fmt ./...

# Vet code
vet:
	go vet ./...

# Clean build artifacts
clean:
	rm -rf bin/ dist/ coverage.out overlord
