# ==============================================================================
# Base Makefile - Git Worktree Commands
# Generated by overlord - Do not edit manually (use overlord sync)
# ==============================================================================

.PHONY: help worktree-new worktree-list worktree-remove worktree-setup

# Default worktree directory (inside project)
WORKTREE_DIR := .worktrees

# Show available commands
help:
	@echo "Worktree Commands:"
	@echo "  make worktree-new BRANCH=<name>    Create new worktree for branch"
	@echo "  make worktree-list                 List all worktrees"
	@echo "  make worktree-remove BRANCH=<name> Remove a worktree"
	@echo "  make worktree-setup                Run setup script in current worktree"
	@echo ""

# Create a new worktree
# Usage: make worktree-new BRANCH=feature-branch
worktree-new:
ifndef BRANCH
	$(error BRANCH is required. Usage: make worktree-new BRANCH=<branch-name>)
endif
	@mkdir -p $(WORKTREE_DIR)
	@if git show-ref --verify --quiet refs/heads/$(BRANCH); then \
		echo "Branch '$(BRANCH)' exists, creating worktree..."; \
		git worktree add $(WORKTREE_DIR)/$(BRANCH) $(BRANCH); \
	else \
		echo "Creating new branch '$(BRANCH)' and worktree..."; \
		git worktree add -b $(BRANCH) $(WORKTREE_DIR)/$(BRANCH); \
	fi
	@echo ""
	@echo "Worktree created at: $(WORKTREE_DIR)/$(BRANCH)"
	@echo "Run 'cd $(WORKTREE_DIR)/$(BRANCH) && make worktree-setup' to initialize"

# List all worktrees
worktree-list:
	@git worktree list

# Remove a worktree
# Usage: make worktree-remove BRANCH=feature-branch
worktree-remove:
ifndef BRANCH
	$(error BRANCH is required. Usage: make worktree-remove BRANCH=<branch-name>)
endif
	@git worktree remove $(WORKTREE_DIR)/$(BRANCH)
	@echo "Worktree '$(BRANCH)' removed"

# Run setup script in current worktree
# Looks for .worktree-setup.sh in the project root
worktree-setup:
	@if [ -f .worktree-setup.sh ]; then \
		echo "Running .worktree-setup.sh..."; \
		chmod +x .worktree-setup.sh && ./.worktree-setup.sh; \
	else \
		echo "No .worktree-setup.sh found. Create one for custom setup."; \
	fi
