# ==============================================================================
# Python Makefile - UV Commands
# Generated by overlord - Do not edit manually (use overlord sync)
# ==============================================================================

.PHONY: install sync lock run test lint format clean

# Install dependencies
install:
	uv sync

# Sync dependencies (same as install for uv)
sync:
	uv sync

# Update lock file
lock:
	uv lock

# Run the project (adjust as needed)
run:
	uv run python -m $(shell basename $(CURDIR))

# Run tests
test:
	uv run pytest

# Lint code
lint:
	uv run ruff check .

# Format code
format:
	uv run ruff format .

# Clean build artifacts
clean:
	rm -rf __pycache__ .pytest_cache .ruff_cache dist build *.egg-info
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
