# ==============================================================================
# Solidity Makefile - Forge Commands
# Generated by overlord - Do not edit manually (use overlord sync)
# ==============================================================================

.PHONY: install build test snapshot gas coverage deploy clean

# Install dependencies
install:
	forge install

# Build contracts
build:
	forge build

# Run tests
test:
	forge test

# Run tests with verbosity
test-v:
	forge test -vvv

# Update gas snapshot
snapshot:
	forge snapshot

# Show gas report
gas:
	forge test --gas-report

# Run coverage
coverage:
	forge coverage

# Deploy (requires DEPLOY_SCRIPT to be set)
deploy:
ifndef DEPLOY_SCRIPT
	$(error DEPLOY_SCRIPT is required. Usage: make deploy DEPLOY_SCRIPT=script/Deploy.s.sol)
endif
	forge script $(DEPLOY_SCRIPT) --broadcast

# Clean build artifacts
clean:
	forge clean
