# ==============================================================================
# TypeScript Makefile - PNPM/Bun Commands
# Generated by overlord - Do not edit manually (use overlord sync)
# ==============================================================================

.PHONY: install build dev test lint format clean

# Detect package manager (prefer bun if bun.lockb exists, else pnpm)
PM := $(shell if [ -f bun.lockb ]; then echo "bun"; else echo "pnpm"; fi)

# Install dependencies
install:
	$(PM) install

# Build the project
build:
	$(PM) run build

# Run development server
dev:
	$(PM) run dev

# Run tests
test:
	$(PM) run test

# Lint code
lint:
	$(PM) run lint

# Format code
format:
	$(PM) run format

# Clean build artifacts
clean:
	rm -rf dist node_modules/.cache .turbo
